EASY-2127 update README.md and test-resources
DANS-KNAW/easy-sword2-dans-examples pull request #24
Opened 2019-06-07 11:25 UTC by rkruithof

fixes EASY-2127

#### When applied it will
* update the readme to provide a more comprehensive introduction
* copy two new examples to the noaccess-flow directory
* update all test doi's to conform to Datacite's new standard

#### Where should the reviewer @DANS-KNAW/easy start?

2019-06-07 12:43 UTC, stephanHogenboom reviewed
Looks good

2019-06-07 12:43 UTC, stephanHogenboom commented on README.md
> +Examples of bags which meet the specifications of the SWORD depositing interface can be found in the [resources directory]. These bags are categorized by the flow which they are designed for.
```suggestion
Examples of bags which meet the specifications of the SWORD depositing interface can be found in the [resources directory](tree/master/src/main/resources). These bags are categorized by the flow which they are designed for.
```

2019-06-07 12:43 UTC, stephanHogenboom commented on README.md
> +[resources directory]: https://github.com/DANS-KNAW/easy-sword2-dans-examples/tree/master/src/main/resources
```suggestion
[resources directory](tree/master/src/main/resources)
```

2019-06-07 12:43 UTC, stephanHogenboom commented on README.md
> +[EASY SWORDv2 deposit documentation page]: https://easy.dans.knaw.nl/doc/sword2.html
```suggestion
[EASY SWORDv2 deposit documentation page](https://easy.dans.knaw.nl/doc/sword2.html)
```

2019-06-07 12:43 UTC, stephanHogenboom commented on README.md
> +[BagIt]: https://datatracker.ietf.org/doc/draft-kunze-bagit
```suggestion
[BagIt](https://datatracker.ietf.org/doc/draft-kunze-bagit)
```

2019-06-07 12:43 UTC, stephanHogenboom commented on README.md
> +[DANS BagIt Profile]: https://github.com/DANS-KNAW/dans-bagit-profile/blob/master/versions/0.0.0.md
```suggestion
[DANS BagIt Profile](../dans-bagit-profile/blob/master/versions/0.0.0.md)
```

2019-06-07 12:43 UTC, stephanHogenboom commented on src/main/resources/README.md
>  [Ingest-flow specs]: https://github.com/DANS-KNAW/easy-specs/blob/master/easy-ingest-flow/easy-ingest-flow.md
```suggestion
[Ingest-flow specs](../easy-specs/blob/master/easy-ingest-flow/easy-ingest-flow.md)
```

2019-06-14 09:27 UTC, janvanmansum commented on README.md
> +1. From your account manager at DANS request access to the acceptance test server. In order to access the acceptance test server your IP address (range) needs to be whitelisted.
Whitelisting is no longer necessary.

2019-06-14 09:29 UTC, janvanmansum commented on README.md
> +1. From your account manager at DANS request access to the acceptance test server. In order to access the acceptance test server your IP address (range) needs to be whitelisted.
```suggestion
1. From your account manager at DANS request access to the acceptance test server. The account manager will provide the information necessary to connect.
```

2019-06-14 09:29 UTC, janvanmansum commented on README.md
> +4. From your account manager at DANS inquire which flow the account is configured for.
```suggestion
4. From your account manager at DANS inquire which flow (see next section) the account is configured for.
```

2019-06-14 09:30 UTC, janvanmansum commented on README.md
> +-------------------------------------
```suggestion
---------------
```

2019-06-14 09:32 UTC, janvanmansum commented on README.md
> +The SWORD service will automatically select a flow for the data when a deposit is submitted. The flow that is selected depends on the agreement between the client company and DANS. The following is a
```suggestion
The SWORD service will automatically select a flow for the data when a deposit is submitted. The flow that is selected depends on the agreement between the depositor organization and DANS. The flow configured for your account will be one of the following:
```

2019-06-14 09:33 UTC, janvanmansum commented on README.md
> +* `Default` - this flow is only for internal use.
```suggestion
```

2019-06-14 09:45 UTC, janvanmansum commented on README.md
> +* `Agreement` - this means a Depositor License Agreement Contract is in place. The datasets will be disseminated by DANS.
```suggestion
* `Agreement` - The datasets will be disseminated by DANS. DANS will mint a DOI for the datasets. 
```

2019-06-14 09:46 UTC, janvanmansum commented on README.md
> +* `NoAccess` - the files are not to be disseminated by DANS.
```suggestion
* `NoAccess` - the files are not to be disseminated by DANS. The depositor organization must mint DOIs for the datasets.
```

2019-06-14 09:46 UTC, janvanmansum commented on README.md
> +The primary difference between the no-access flow and the other flows is that the no-access flow requires a DOI to be present in the metadata.xml.
```suggestion
``

2019-06-14 10:10 UTC, janvanmansum requested changes
Look already much better! Some things can be improved still, as discussed off-line:

* Extend "Getting started" to include a *concrete* example of running the SimpleDeposit program (with the example deposit to send depending on the flow type of course).
* Move the more general info about the various types of deposits you can send to a sections after "Getting started".
* Check if you can improve the part about output analysis by pretty printing the XML (Search for a way to do that in Java, see for example https://stackoverflow.com/questions/139076/how-to-pretty-print-xml-from-java for a starting point.
* Side issue (as discussed): check what happens when you send an *update* deposit for an Agreement-account and you provide the previously minted DANS-DOI in the dataset.xml.

2019-06-14 10:11 UTC, janvanmansum commented on README.md
> +[xmllint] : http://xmlsoft.org/xmllint.html
```suggestion
[xmllint]: http://xmlsoft.org/xmllint.html
```

Always check if your Markdown renders correctly!

2019-06-14 17:11 UTC, janvanmansum commented
It is not completely as I would like it, but a major improvement over what we had, so I'll merge it anyway.

2019-06-14 17:11 UTC, merged